task: "train_cv"
clinic_path: ""
FEATURES: ""
resFolder: ""

model_name: "UNI" 
attention: "MultiHeadAttention"
stainFunc: "augmentation"
TC_epi: 0.9
bag_size: 250 

split_ratio: 0.8
aug_prob: 0.5
n_classes: 3
n_heads: 8
n_latent: 512
attn_dropout: 0.5
attn_temp: 0.5
batch_size: 16
lr: 0.00001
weight_decay: 0.00005
patience: 10
max_epochs: 200

ckpt_pt: ""
